export const INSPIRATIONAL_PHRASES = [
  "A sabedoria constrói com paciência aquilo que a pressa não consegue sustentar.",
  "Como José no Egito, organize hoje para atravessar melhor as próximas estações.",
  "A diligência abre caminhos onde a desordem só enxerga obstáculos.",
  "Quem age com prudência protege o fruto do próprio trabalho.",
  "Como Neemias, reconstrua uma parte por vez, com foco e coragem.",
  "A resposta branda preserva relacionamentos e abre espaço para bons acordos.",
  "Planejar bem também é uma forma de honrar o que foi confiado às suas mãos.",
  "A balança justa começa nas pequenas decisões do dia.",
  "Como Daniel, mantenha excelência mesmo quando ninguém está olhando.",
  "O coração sábio mede os passos antes de assumir novos compromissos.",
  "A constância transforma pequenas tarefas em grandes resultados.",
  "Onde há conselho sábio, há menos tropeços no caminho.",
  "Como Moisés, conduza com paciência até quando a jornada parecer longa.",
  "A prudência evita perdas que depois custariam caro corrigir.",
  "Trabalho bem feito é semente plantada para uma colheita melhor.",
  "A sabedoria começa quando a humildade aceita aprender.",
  "Como Davi diante de Golias, vença hoje uma grande tarefa com fé e preparo.",
  "Quem guarda a palavra também guarda a direção.",
  "A organização de hoje pode ser o livramento de amanhã.",
  "Com mãos diligentes, o pouco ganha forma e o muito ganha ordem.",
  "Como Salomão, peça sabedoria antes de pedir grandes resultados.",
  "O justo cuida dos detalhes porque sabe que fidelidade também mora neles.",
  "A pressa promete ganho, mas a prudência preserva o caminho.",
  "Como Rute, seja fiel no pequeno campo que está diante de você.",
  "A disciplina silenciosa prepara vitórias visíveis.",
  "O bom nome vale mais que ganhos apressados.",
  "Quem ouve antes de decidir reduz riscos e aumenta clareza.",
  "Como Ester, há decisões que pedem coragem no tempo certo.",
  "A sabedoria protege a casa, os planos e o trabalho.",
  "Semeie ordem, colha tranquilidade.",
  "Como Noé, construa com obediência mesmo antes de ver a chuva.",
  "O trabalho diligente prospera quando caminha com honestidade.",
  "A prudência não atrasa o crescimento; ela sustenta o crescimento.",
  "Como Abraão, caminhe com fé sem abandonar a responsabilidade.",
  "A boca sábia evita conflitos que a força não resolveria.",
  "Melhor ajustar hoje do que reparar grandes perdas amanhã.",
  "Como Josué, avance com coragem e atenção ao que precisa ser feito.",
  "A sabedoria transforma números em direção e decisões em paz.",
  "Quem administra com justiça fortalece o futuro.",
  "A fidelidade no processo prepara a colheita no tempo certo.",
  "Como a formiga de Provérbios, antecipe-se com diligência e organização.",
  "O coração prudente revisa o caminho antes de acelerar.",
  "Uma decisão sábia hoje pode proteger muitos dias à frente.",
  "Como José, não desperdice tempos de abundância; organize-os com propósito.",
  "A bênção também encontra espaço em ambientes bem cuidados.",
  "Quem corrige a rota cedo evita longas voltas depois.",
  "A sabedoria sabe quando falar, quando ouvir e quando esperar.",
  "Como Samuel, aprenda a reconhecer a direção antes de agir.",
  "A excelência é feita de pequenas fidelidades repetidas.",
  "O ganho honesto pode crescer devagar, mas permanece de pé.",
  "Como Elias, descanse quando for preciso e volte ao caminho com clareza.",
  "A prudência pesa o compromisso antes de assinar o caminho.",
  "Trabalho com propósito transforma rotina em missão.",
  "Como Gideão, comece com o que está em suas mãos.",
  "A sabedoria evita atalhos que cobram juros altos depois.",
  "Quem cuida bem do presente prepara um futuro mais leve.",
  "Como os servos nas bodas de Caná, faça bem sua parte e confie no resultado.",
  "O planejamento humilde reconhece limites e encontra caminhos.",
  "A disciplina guarda o coração das decisões impulsivas.",
  "Como Pedro, recomece com coragem depois de aprender com a queda.",
  "Um dia bem organizado é uma resposta prática à ansiedade.",
  "Quem anda com sabedoria escolhe melhor os próximos passos.",
  "Como Paulo, mantenha foco mesmo em jornadas difíceis.",
  "A prosperidade saudável caminha junto com justiça e domínio próprio.",
  "A clareza evita cobranças confusas e fortalece relacionamentos.",
  "Como Barnabé, encoraje pessoas enquanto constrói resultados.",
  "A sabedoria faz perguntas antes de fechar conclusões.",
  "O cuidado com detalhes pequenos protege decisões grandes.",
  "Como o bom samaritano, excelência também é servir com responsabilidade.",
  "Quem semeia com honestidade pode descansar com a consciência em paz.",
  "A prudência é uma proteção discreta para grandes sonhos.",
  "Como Maria, guarde no coração o que ainda está amadurecendo.",
  "A palavra certa no momento certo pode abrir portas com mansidão.",
  "Organização não é frieza; é cuidado com aquilo que importa.",
  "Como Marta, sirva com dedicação; como Maria, preserve o essencial.",
  "A sabedoria transforma esforço em direção.",
  "Quem aprende com conselho evita repetir dores antigas.",
  "Como Zaqueu, ajuste o que precisa ser ajustado e siga em paz.",
  "A integridade vale mais que qualquer resultado imediato.",
  "O caminho firme nasce de decisões simples tomadas com constância.",
  "Como Timóteo, cresça com disciplina e bom exemplo.",
  "A justiça no pequeno prepara confiança no grande.",
  "Quem organiza vencimentos também organiza tranquilidade.",
  "Como a viúva que ofertou pouco, valorize a fidelidade acima da aparência.",
  "A sabedoria não grita; ela orienta com firmeza.",
  "O controle de hoje evita aperto amanhã.",
  "Como os discípulos no barco, mantenha a fé mesmo quando o vento muda.",
  "A diligência faz a oportunidade encontrar tudo preparado.",
  "Quem administra com temor e clareza constrói sobre base firme.",
  "Como Jacó, aprenda com processos longos e amadureça no caminho.",
  "A verdade simplifica relatórios, acordos e conversas difíceis.",
  "A paz também nasce de contas claras e decisões justas.",
  "Como Ana, apresente seus planos com fé e siga fazendo sua parte.",
  "A sabedoria escolhe consistência acima de aparência.",
  "Quem honra compromissos fortalece o próprio nome.",
  "Como Esdras, prepare o coração antes de ensinar ou decidir.",
  "A visão amadurece quando encontra disciplina diária.",
  "O justo não depende de atalhos para prosperar.",
  "Como Jesus multiplicando os pães, organize o que há antes de servir o muito.",
  "Quem caminha em sabedoria transforma pressão em prioridade.",
] as const;

export function getDailyInspirationalPhrase(seed = "") {
  const today = new Date();
  const dayKey = Math.floor(
    Date.UTC(today.getFullYear(), today.getMonth(), today.getDate()) / 86_400_000,
  );
  const seedValue = Array.from(seed).reduce((sum, char) => sum + char.charCodeAt(0), 0);

  return INSPIRATIONAL_PHRASES[(dayKey + seedValue) % INSPIRATIONAL_PHRASES.length];
}
