/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as ApiWebhookCompraAprovadaRouteImport } from './routes/api/webhook-compra-aprovada'
import { Route as ApiWebhookCancelamentoRouteImport } from './routes/api/webhook-cancelamento'
import { Route as AuthedVencimentosRouteImport } from './routes/_authed.vencimentos'
import { Route as AuthedSuporteRouteImport } from './routes/_authed.suporte'
import { Route as AuthedRelatoriosRouteImport } from './routes/_authed.relatorios'
import { Route as AuthedContratosRouteImport } from './routes/_authed.contratos'
import { Route as AuthedConfiguracoesRouteImport } from './routes/_authed.configuracoes'
import { Route as AuthedClientesRouteImport } from './routes/_authed.clientes'
import { Route as AuthedBemVindoRouteImport } from './routes/_authed.bem-vindo'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiWebhookCompraAprovadaRoute =
  ApiWebhookCompraAprovadaRouteImport.update({
    id: '/api/webhook-compra-aprovada',
    path: '/api/webhook-compra-aprovada',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhookCancelamentoRoute = ApiWebhookCancelamentoRouteImport.update({
  id: '/api/webhook-cancelamento',
  path: '/api/webhook-cancelamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedVencimentosRoute = AuthedVencimentosRouteImport.update({
  id: '/vencimentos',
  path: '/vencimentos',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSuporteRoute = AuthedSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRelatoriosRoute = AuthedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedContratosRoute = AuthedContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedConfiguracoesRoute = AuthedConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientesRoute = AuthedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBemVindoRoute = AuthedBemVindoRouteImport.update({
  id: '/bem-vindo',
  path: '/bem-vindo',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bem-vindo': typeof AuthedBemVindoRoute
  '/clientes': typeof AuthedClientesRoute
  '/configuracoes': typeof AuthedConfiguracoesRoute
  '/contratos': typeof AuthedContratosRoute
  '/relatorios': typeof AuthedRelatoriosRoute
  '/suporte': typeof AuthedSuporteRoute
  '/vencimentos': typeof AuthedVencimentosRoute
  '/api/webhook-cancelamento': typeof ApiWebhookCancelamentoRoute
  '/api/webhook-compra-aprovada': typeof ApiWebhookCompraAprovadaRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bem-vindo': typeof AuthedBemVindoRoute
  '/clientes': typeof AuthedClientesRoute
  '/configuracoes': typeof AuthedConfiguracoesRoute
  '/contratos': typeof AuthedContratosRoute
  '/relatorios': typeof AuthedRelatoriosRoute
  '/suporte': typeof AuthedSuporteRoute
  '/vencimentos': typeof AuthedVencimentosRoute
  '/api/webhook-cancelamento': typeof ApiWebhookCancelamentoRoute
  '/api/webhook-compra-aprovada': typeof ApiWebhookCompraAprovadaRoute
  '/': typeof AuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authed/bem-vindo': typeof AuthedBemVindoRoute
  '/_authed/clientes': typeof AuthedClientesRoute
  '/_authed/configuracoes': typeof AuthedConfiguracoesRoute
  '/_authed/contratos': typeof AuthedContratosRoute
  '/_authed/relatorios': typeof AuthedRelatoriosRoute
  '/_authed/suporte': typeof AuthedSuporteRoute
  '/_authed/vencimentos': typeof AuthedVencimentosRoute
  '/api/webhook-cancelamento': typeof ApiWebhookCancelamentoRoute
  '/api/webhook-compra-aprovada': typeof ApiWebhookCompraAprovadaRoute
  '/_authed/': typeof AuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recuperar-senha'
    | '/reset-password'
    | '/bem-vindo'
    | '/clientes'
    | '/configuracoes'
    | '/contratos'
    | '/relatorios'
    | '/suporte'
    | '/vencimentos'
    | '/api/webhook-cancelamento'
    | '/api/webhook-compra-aprovada'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recuperar-senha'
    | '/reset-password'
    | '/bem-vindo'
    | '/clientes'
    | '/configuracoes'
    | '/contratos'
    | '/relatorios'
    | '/suporte'
    | '/vencimentos'
    | '/api/webhook-cancelamento'
    | '/api/webhook-compra-aprovada'
    | '/'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/recuperar-senha'
    | '/reset-password'
    | '/_authed/bem-vindo'
    | '/_authed/clientes'
    | '/_authed/configuracoes'
    | '/_authed/contratos'
    | '/_authed/relatorios'
    | '/_authed/suporte'
    | '/_authed/vencimentos'
    | '/api/webhook-cancelamento'
    | '/api/webhook-compra-aprovada'
    | '/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiWebhookCancelamentoRoute: typeof ApiWebhookCancelamentoRoute
  ApiWebhookCompraAprovadaRoute: typeof ApiWebhookCompraAprovadaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/webhook-compra-aprovada': {
      id: '/api/webhook-compra-aprovada'
      path: '/api/webhook-compra-aprovada'
      fullPath: '/api/webhook-compra-aprovada'
      preLoaderRoute: typeof ApiWebhookCompraAprovadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook-cancelamento': {
      id: '/api/webhook-cancelamento'
      path: '/api/webhook-cancelamento'
      fullPath: '/api/webhook-cancelamento'
      preLoaderRoute: typeof ApiWebhookCancelamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/vencimentos': {
      id: '/_authed/vencimentos'
      path: '/vencimentos'
      fullPath: '/vencimentos'
      preLoaderRoute: typeof AuthedVencimentosRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/suporte': {
      id: '/_authed/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof AuthedSuporteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/relatorios': {
      id: '/_authed/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthedRelatoriosRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/contratos': {
      id: '/_authed/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AuthedContratosRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/configuracoes': {
      id: '/_authed/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthedConfiguracoesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clientes': {
      id: '/_authed/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthedClientesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/bem-vindo': {
      id: '/_authed/bem-vindo'
      path: '/bem-vindo'
      fullPath: '/bem-vindo'
      preLoaderRoute: typeof AuthedBemVindoRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedBemVindoRoute: typeof AuthedBemVindoRoute
  AuthedClientesRoute: typeof AuthedClientesRoute
  AuthedConfiguracoesRoute: typeof AuthedConfiguracoesRoute
  AuthedContratosRoute: typeof AuthedContratosRoute
  AuthedRelatoriosRoute: typeof AuthedRelatoriosRoute
  AuthedSuporteRoute: typeof AuthedSuporteRoute
  AuthedVencimentosRoute: typeof AuthedVencimentosRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBemVindoRoute: AuthedBemVindoRoute,
  AuthedClientesRoute: AuthedClientesRoute,
  AuthedConfiguracoesRoute: AuthedConfiguracoesRoute,
  AuthedContratosRoute: AuthedContratosRoute,
  AuthedRelatoriosRoute: AuthedRelatoriosRoute,
  AuthedSuporteRoute: AuthedSuporteRoute,
  AuthedVencimentosRoute: AuthedVencimentosRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiWebhookCancelamentoRoute: ApiWebhookCancelamentoRoute,
  ApiWebhookCompraAprovadaRoute: ApiWebhookCompraAprovadaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
