// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const PROJECT_REF = (import.meta.env.VITE_SUPABASE_PROJECT_ID as string | undefined) ?? '';
export const SUPABASE_AUTH_COOKIE = PROJECT_REF
  ? `sb-${PROJECT_REF}-auth-token`
  : 'sb-auth-token';

/**
 * Storage adapter que escreve em localStorage E em um cookie HTTP.
 *
 * O cookie permite ao servidor (TanStack Start `beforeLoad`) ler a sessão
 * Supabase ANTES de qualquer renderização — base da proteção server-side
 * de rotas privadas (Cortina de Ferro).
 *
 * - SameSite=Lax: enviado em navegações top-level (necessário para SSR
 *   funcionar em links externos / refresh).
 * - Secure: apenas em produção (HTTPS). Em dev (localhost) precisa ficar
 *   off senão o browser ignora o cookie.
 * - Path=/: disponível em todas as rotas.
 * - Max-Age 30 dias: alinhado com o refresh-token padrão do Supabase.
 */
function createCookieAndLocalStorage(): Storage {
  const KEY = SUPABASE_AUTH_COOKIE;
  const isHttps =
    typeof window !== 'undefined' && window.location.protocol === 'https:';
  const cookieAttrs = `Path=/; SameSite=Lax; Max-Age=2592000${isHttps ? '; Secure' : ''}`;

  const writeCookie = (name: string, value: string) => {
    if (typeof document === 'undefined') return;
    // Encoda para evitar caracteres inválidos em cookies (a sessão é JSON).
    document.cookie = `${name}=${encodeURIComponent(value)}; ${cookieAttrs}`;
  };
  const deleteCookie = (name: string) => {
    if (typeof document === 'undefined') return;
    document.cookie = `${name}=; Path=/; Max-Age=0; SameSite=Lax${isHttps ? '; Secure' : ''}`;
  };

  return {
    getItem: (key: string) => {
      try {
        return window.localStorage.getItem(key);
      } catch {
        return null;
      }
    },
    setItem: (key: string, value: string) => {
      try {
        window.localStorage.setItem(key, value);
      } catch {
        /* ignore */
      }
      // Mirror APENAS a chave de auth no cookie. Outras chaves ficam só em LS.
      if (key === KEY) writeCookie(key, value);
    },
    removeItem: (key: string) => {
      try {
        window.localStorage.removeItem(key);
      } catch {
        /* ignore */
      }
      if (key === KEY) deleteCookie(key);
    },
    // Stubs obrigatórios da interface Storage:
    key: () => null,
    clear: () => {
      try {
        window.localStorage.clear();
      } catch {
        /* ignore */
      }
      deleteCookie(KEY);
    },
    length: 0,
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      'Missing Supabase environment variables. Ensure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY (or VITE_ prefixed versions) are set in your .env file.'
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? createCookieAndLocalStorage() : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
